//! Prometheus metrics export for the MPC node (Issue #101).
//!
//! Mirrors the coordinator's `prometheus`-crate pattern (see
//! `services/coordinator/src/main.rs`) so both services expose a `/metrics`
//! text endpoint in the same format. Tracks the three signals the issue asks
//! for: active sessions, proofs generated, and error counts (by phase, so a
//! spike in e.g. `witness_generation` errors is distinguishable from
//! `proof_generation` errors).

use axum::{body::Body, http::Response};
use prometheus::{Encoder, Gauge, GaugeVec, IntCounterVec, IntGauge, Opts, Registry, TextEncoder};

#[derive(Clone)]
pub struct NodeMetrics {
    registry: Registry,
    /// Number of MPC sessions currently running witness/proof generation.
    pub active_sessions: IntGauge,
    /// Proofs successfully generated, labeled by circuit name.
    pub proofs_generated: IntCounterVec,
    /// Session errors, labeled by the phase in which they occurred
    /// (e.g. "merge_shares", "witness_generation", "proof_generation").
    pub session_errors: IntCounterVec,
    /// Node health status: 1 = healthy, 0 = unhealthy.
    pub node_up: Gauge,
    /// Process resident memory in bytes.
    pub memory_bytes: Gauge,
    /// Memory limit in bytes (from cgroups or env).
    pub memory_limit_bytes: Gauge,
    /// Clock skew in seconds (node time vs coordinator time).
    pub clock_skew_seconds: Gauge,
    /// Days until TLS certificate expires.
    pub cert_expiry_days: GaugeVec,
}

impl NodeMetrics {
    pub fn new() -> Self {
        let registry = Registry::new();

        let active_sessions = IntGauge::with_opts(Opts::new(
            "mpc_node_active_sessions",
            "Number of MPC sessions currently in witness/proof generation.",
        ))
        .unwrap();

        let proofs_generated = IntCounterVec::new(
            Opts::new(
                "mpc_node_proofs_generated_total",
                "Total number of proofs successfully generated by this node.",
            ),
            &["circuit"],
        )
        .unwrap();

        let session_errors = IntCounterVec::new(
            Opts::new(
                "mpc_node_session_errors_total",
                "Total number of MPC session errors, labeled by phase.",
            ),
            &["phase"],
        )
        .unwrap();

        let node_up = Gauge::with_opts(Opts::new(
            "mpc_node_up",
            "Node health status: 1 = healthy, 0 = unhealthy.",
        ))
        .unwrap();

        let memory_bytes = Gauge::with_opts(Opts::new(
            "mpc_node_memory_bytes",
            "Process resident memory in bytes.",
        ))
        .unwrap();

        let memory_limit_bytes = Gauge::with_opts(Opts::new(
            "mpc_node_memory_limit_bytes",
            "Memory limit in bytes (from cgroups or env).",
        ))
        .unwrap();

        let clock_skew_seconds = Gauge::with_opts(Opts::new(
            "mpc_node_clock_skew_seconds",
            "Clock skew in seconds (node time vs coordinator time).",
        ))
        .unwrap();

        let cert_expiry_days = GaugeVec::new(
            Opts::new(
                "mpc_node_cert_expiry_days",
                "Days until TLS certificate expires.",
            ),
            &["cert_type"],
        )
        .unwrap();

        registry
            .register(Box::new(active_sessions.clone()))
            .unwrap();
        registry
            .register(Box::new(proofs_generated.clone()))
            .unwrap();
        registry.register(Box::new(session_errors.clone())).unwrap();
        registry.register(Box::new(node_up.clone())).unwrap();
        registry.register(Box::new(memory_bytes.clone())).unwrap();
        registry
            .register(Box::new(memory_limit_bytes.clone()))
            .unwrap();
        registry
            .register(Box::new(clock_skew_seconds.clone()))
            .unwrap();
        registry
            .register(Box::new(cert_expiry_days.clone()))
            .unwrap();

        Self {
            registry,
            active_sessions,
            proofs_generated,
            session_errors,
            node_up,
            memory_bytes,
            memory_limit_bytes,
            clock_skew_seconds,
            cert_expiry_days,
        }
    }

    pub fn render(&self) -> Vec<u8> {
        let metric_families = self.registry.gather();
        let encoder = TextEncoder::new();
        let mut buffer = Vec::new();
        encoder.encode(&metric_families, &mut buffer).unwrap();
        buffer
    }
}

impl Default for NodeMetrics {
    fn default() -> Self {
        Self::new()
    }
}

/// GET /metrics
pub async fn metrics_endpoint(
    axum::extract::State(state): axum::extract::State<crate::NodeState>,
) -> Response<Body> {
    let buffer = state.metrics.render();
    Response::builder()
        .status(200)
        .header("Content-Type", TextEncoder::new().format_type())
        .body(Body::from(buffer))
        .unwrap()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn active_sessions_gauge_tracks_inc_dec() {
        let metrics = NodeMetrics::new();
        assert_eq!(metrics.active_sessions.get(), 0);
        metrics.active_sessions.inc();
        metrics.active_sessions.inc();
        assert_eq!(metrics.active_sessions.get(), 2);
        metrics.active_sessions.dec();
        assert_eq!(metrics.active_sessions.get(), 1);
    }

    #[test]
    fn proofs_generated_counted_by_circuit() {
        let metrics = NodeMetrics::new();
        metrics.proofs_generated.with_label_values(&["deal"]).inc();
        metrics.proofs_generated.with_label_values(&["deal"]).inc();
        metrics
            .proofs_generated
            .with_label_values(&["showdown_valid"])
            .inc();
        assert_eq!(
            metrics.proofs_generated.with_label_values(&["deal"]).get(),
            2
        );
        assert_eq!(
            metrics
                .proofs_generated
                .with_label_values(&["showdown_valid"])
                .get(),
            1
        );
    }

    #[test]
    fn session_errors_counted_by_phase() {
        let metrics = NodeMetrics::new();
        metrics
            .session_errors
            .with_label_values(&["witness_generation"])
            .inc();
        assert_eq!(
            metrics
                .session_errors
                .with_label_values(&["witness_generation"])
                .get(),
            1
        );
        assert_eq!(
            metrics
                .session_errors
                .with_label_values(&["proof_generation"])
                .get(),
            0
        );
    }

    #[test]
    fn render_produces_prometheus_text_format() {
        let metrics = NodeMetrics::new();
        metrics.active_sessions.inc();
        let text = String::from_utf8(metrics.render()).unwrap();
        assert!(text.contains("mpc_node_active_sessions 1"));
    }
}
