version: "3.8"

services:
  influxdb:
    image: influxdb:1.8
    container_name: stellpoker-k6-influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb:/var/lib/influxdb

  prometheus:
    image: prom/prometheus:latest
    container_name: stellpoker-k6-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus-alerting-rules.yml:/etc/prometheus/prometheus-alerting-rules.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  alertmanager:
    image: prom/alertmanager:latest
    container_name: stellpoker-k6-alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"

  grafana:
    image: grafana/grafana:latest
    container_name: stellpoker-k6-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    depends_on:
      - influxdb
      - prometheus
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards

  k6:
    image: grafana/k6:latest
    working_dir: /scripts
    volumes:
      - ./k6:/scripts
    entrypoint: ["/bin/sh", "-c", "sleep infinity"]
